### ISSUE TITLE
Dropdown is not behaving correctly

### ISSUE THREAD

**Issue by Foxandxss** [ng-bootstrap/core#109]
Yay, first real issue.

The dropdown as is as we have it now (even with pawel changes on toggle) is not working right on the CSS.

Check this [plunker](http://plnkr.co/edit/X5nOU0W2F9QPW2IX913R?p=preview)

First two works good, the third one doesnt.

There seems to be a dropdown and button dropdown. First two are button dropdown (they need a `btn-group`) and the third one which is the raw one (the one we support directly) has the popup weirdly.

**Comment by pkozlowski-opensource** [comment]
This is because of our choice to use element directives for dropdown. When you use an attribute it all works as expected: http://plnkr.co/edit/6e0TFcrlFXMQpuAWzvPO?p=preview

It seems like dropdown needs to be a block element but unknown elements are interpreted as inline by default (http://www.impressivewebs.com/default-css-display-values-html-elements/)

IMO we should have `ngb-dropdown`  as an attribute.

**Comment by Foxandxss** [comment]
Weird, thought that I tried that too when I was playing with it. I was also going to recommend that change too.
