### ISSUE TITLE
[Proposal] Angular-ui?

### ISSUE THREAD

**Issue by ProLoser** [ng-bootstrap/core#171]
I won't take offense if you decline (as it's become quite common for this project to grow and split apart) lol.

Do you guys have any interest in using the angular-ui namespace? You can put together whatever teams/repos you'd need and can make you co-owners of the org.

**Comment by Foxandxss** [comment]
Hello Dean,

We decided to create our own organization because we would like to create different repositories for different kind of components, engines and other stuff.

We thought that it would be too messy to have it at angular-ui because that has a lot of repos already and adding a bunch of extra repos would be confusing.

Cheers.
