### ISSUE TITLE
Rating: decide on how to display stars

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#318]
As of today we are adding `` and `` CSS classes but those classes are not part of Bootstrap's CSS. We need to either:
* add dependency on an external lib / font 
* include required classes as part of the wdiget
* use UTF character
* figure out sth else :-)

**Comment by icfantv** [comment]
i say initially release w/ some default entity character (if possible) or UTF-8 (if possible, sounds like IE9 was an issue?) and then provide an interface to let the user use their own fonts.  I suspect strongly that with the removal of glyphicons from BS4 and the switch to a pay model, folks will be flocking to Font Awesome in droves.  That said, IMO, we should not impose any font decision on anyone - and I realize no one is suggesting that...

**Comment by maxokorokov** [comment]
I did a bit of research and as fast/ugly solution there are two entities &#9733; (&amp;#9733;) and &#9734; (&amp;#9734;) that seem to render for me in the IE9, IE11, Safari, Firefox. They look quite ugly in IE because of antialiasing though, but so do all other symbols.

Secondly, all the major icon providers render in the same way ([from here](http://tagliala.github.io/vectoriconsroundup/)):

- Font Awesome `<i class="fa fa-star"></i>`
- Glyphicons `<i class="glyphicon glyphicon-star"></i>`
- Material Design `<i class="mdi mdi-star"></i>`
- Ionicons `<i class="ion-star"></i>`
- Foundation Icon Fonts `<i class="fi-star"></i>`
- Elusive Icons `<i class="el el-star"></i>`

So looks like giving the ability to simply specify 'on' and 'off' classes in the rating component would cover these use cases. And fallback to the mentioned characters if nothing specified. Plus there might be a global component configuration to avoid setting this on a per-instance basis

Another option would be to allow user to provide a template element, but this is an overkill I think.

**Comment by sendilkumarn** [comment]
@maxokorokov  option 1 👍

**Comment by Foxandxss** [comment]
I like the UTF entities but for some reason I discarded it while I was creating a guide for angular.io and I don't remember why.

We need icons with a good license.

**Comment by pkozlowski-opensource** [comment]
Thnx @maxokorokov for a good research on the topic. How about we do things like this:
* let's use entities for alpha.0
* as soon as we've got global config (providers) for directives we could add 2 `@Input`s to the rating (`onClass` / `offClass`) and use those classes (or entities if classes not provided / configured).

At least this way we've got a working widget and as soon as people start to complain about look & feel we will have an answer for them (in the form of CSS class config). 

Having said all this I kind of agree with @Foxandxss that we will need to commit to more icons in the future as we will need some additional ones for date / time pickers.

**Comment by Foxandxss** [comment]
Let's use UTF characters today. Swap it if needed to something else.

UTF characters have no dependencies and works fine. Better than adding one of those fonts and then realize we don't want it.

**Comment by icfantv** [comment]
I agree

**Comment by mendeza** [comment]
I agree to use UTF-8. Just keep in mind that users will want to customize and not necessarily use the star symbol. Perhaps make this configurable fro the beginning?

Just to play devil's advocate, you could also consider dropping the Rating component. It is easily made from scratch. And you could avoid extra CSS.

**Comment by Foxandxss** [comment]
No, not drop it. Is easy to be made but not easy to be made right. It needs a lot of a11y stuff.
