### ISSUE TITLE
To card or not to card?

### ISSUE THREAD

**Issue by Foxandxss** [ng-bootstrap/core#50]
So, there is a new kind of panel called Card.

An example would be http://plnkr.co/edit/eaGaEpds72KQlL0YrgRO?p=preview

I don't think we should create a component for this, but potentially update the templates to use cards where it makes sense.

The downside is that we lose the possibility to reuse those templates for bootstrap 3.x

Thoughts?

**Comment by wesleycho** [comment]
I don't think we should support these in a component - I already investigated this, and it seems too limited given what Bootstrap's markup supports.

I wouldn't be against using cards where they would make sense, but we should consider a way to allow users to break out of opinionated markup in our components.

**Comment by wesleycho** [comment]
For reference: http://v4-alpha.getbootstrap.com/components/card/

**Comment by thatguyyoulove** [comment]
I would agree with you both. It doesn't make sense as a component.

**Comment by wesleycho** [comment]
Closing as won't support

**Comment by thekalinga** [comment]
Is there a reason why `ng-bootstrap` be compatible with bootstrap 3?

This project should be compatible with bootstrap 4 & forward

ng-bootstrap should be forward looking, so it makes very little sense to close this issue.

**Comment by thekalinga** [comment]
Keep the issue open so that interested contributors would contribute, rather than blindly closing this issue

**Comment by yehia2amer** [comment]
Why to use Cards:
1) Because it is simple as hell
2) the syntax is very clear and readable
3) The concept of cards is very popular nowadays in web development
4) why do we have to reinvent the wheel
5) bootstrap 4 replaced panels with cards so it is better to be aligned with it !

I think that this decision should be revisited

**Comment by paustint** [comment]
> Because it is simple as hell
Because cards are so simple, I don't think it makes sense to abstract that into an ngb component and complicate the simple card structure offered by BS.

This ticket is 1 1/2 years old and cards have been incorporated in various areas.  This library does make an artificial "panel" on the accordion (which is not a native BS4 construct), but it is made up of the card component behind the scenes.

My vote is to leave this ticket closed, as there is not really anything actionable based on the information in this ticket.
