### ISSUE TITLE
Discuss conventions: element vs. attribute selector

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#90]
We start to have different approaches to `@Directive` selectors: compare accordion that uses _both_ element and attribute vs. dropdown that uses element for something that could be an attribute.

**Comment by Foxandxss** [comment]
I don't think that it is more of a Directive or Component things.

If a component (as generic components, not @Component) is meant to be a whole widget like an accordion, it is better to leave it as element:

```html
<accordion>
  <group></group>
  <group></group>
  <group></group>
</accordion>
```

It would be weird to use it as attribute (I put it on our accordion because that existed in uibs)

On the other hand, if you have a component that is meant to modify a behavior, you should use attribute:

```
<input [(ng-model)]="date" ngb-datepicker-popup ...>
```

It doesn't make sense to use element in there.

**Comment by pkozlowski-opensource** [comment]
> If a component (as generic components, not @Component) is meant to be a whole widget like an accordion, it is better to leave it as element

Agreed. This is why I was wondering why you've decided to mark accordion as both an element and an attribute.

**Comment by Foxandxss** [comment]
First implementation was a bit straight from uibs to get my feet wet. I will file a PR.

**Comment by pkozlowski-opensource** [comment]
I think that this one is resolved.
